### PR TITLE
Better local_request

### PR DESCRIPTION
**Pull request by wojcikstefan**
* Supports methods other than GET
* Returns a status code, not just the data

### CODE REVIEW

**Comment by lucasvo** [comment]
Can this method be used to call the closeio api from within another request?

**Comment by wojcikstefan** [comment]
@lucasvo yup

**Comment by philfreo** [comment]
@lucasvo If you have an API key for the user we already can do that easily with `app.fake_api`

**Comment by thomasst** [comment]
Desperately needs a docstring.

**Comment by lucasvo** [comment]
@philfreo this might be interesting for the billing api case. would get us much closer to a real service than what we're currently doing.

**Comment by philfreo** [comment]
@lucasvo yup. we're already using fake_api and local_request in multiple places, would recommend it

**Pull request merged**
