### PR TITLE
Add all packages in setup.py

### PR DESCRIPTION
**Pull request by mpessas**

### CODE REVIEW

**Comment by thomasst** [comment]
What does this do? Why do we need this?

**Comment by mpessas** [comment]
It includes the subpackages `flask_common.utils` and `flask_common.fields' ` in the built package. Without that, running `pip install git+https://github.com/closeio/flask-common.git#egg=flask_common` leaves those directories out of the package.

**Comment by tsx** [comment]
My guess is that we need this to be able to drop `-e` from `requirements.txt` in other repos that depend on this one. Is that correct @mpessas ?

**Comment by mpessas** [comment]
It is @tsx. However, without the change the `setup.py` file is not correct in the first place.

**Pull request merged**
