### PR TITLE
Support comparator in uniqify

### PR DESCRIPTION
**Pull request by charliewolf**

### CODE REVIEW

**Comment by thomasst** [comment]
Looks good, here's my feedback:

* Rename `key_comparator` to `key` to be consisted with Python's `sorted(key=lambda: ...)` (also, the function is not technically comparing two items, it's simply extracting the keys that will be compared)
* Add explanation and/or an example to the doc string.

**Comment by charliewolf** [comment]
@thomasst Updated

**Comment by thomasst** [comment]
Great, and sorry, forgot to mention to add a test case in `tests/__init__.py` under `UtilsTestCase.test_uniqify`. Then it should be good to go.

**Comment by charliewolf** [comment]
Roger that. See latest commit.

**Pull request merged**
